config/routes.rb
Puppal::Application.routes.draw do
  root :to => 'dogs#index'
  resources :dogs

  match 'location' => 'dogs#location'
  match 'priority' => 'dogs#priority'
  match 'bios' => 'dogs#bios'
  match 'photos' => 'dogs#photos'
  match 'videos' => 'dogs#videos'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  validates :name, :presence => true
  attr_accessible :bio, :name, :notes, :photo, :priority, :site, :video
  # belongs_to :site, :foreign_key => 'id'

  # Order dogs alphabetically
  scope :alphabetically, order("name ASC")

  # Find by Site
  scope :tlac, where(site: 'TLAC')
  scope :mueller, where(site: '51st and Mueller')
  scope :brodie, where(site: 'Brodie')
  scope :soco, where(site: 'SoCo')
  scope :lakeline, where(site: 'Lakeline')

  # Find by Priority
  scope :high, where(priority: 1)
  scope :med, where(priority: 2)
  scope :low, where(priority: 3)

  # Find by Need
  scope :needphotos, where(photo:'Incomplete')
  scope :needvideos, where(video:'Incomplete')
  scope :needbios, where(bio:'Incomplete')

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :bio, :name, :notes, :photo, :priority, :site, :video
  # has_many :dogs, :foreign_key => 'id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    def redirect_to(options = {}, response_status = {})
    if request.xhr?
      render(:update) {|page| page.redirect_to(options)}
    else
      super(options, response_status)
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # GET /dogs
  # GET /dogs.json
  # GET /dogs.json


  
  def index
    @dogs = Dog.alphabetically
    @dog = Dog.new(params[:dog])  

   # respond_to do |format|
   #    format.html 
   #    format.js
   #  end

  end


  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dog }
      format.js 

    end
  end

  # GET /dogs/new
  # GET /dogs/new.json
  def new
    @dog = Dog.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dog }
      format.js 
    end    
  end

  # GET /dogs/1/edit
  def edit
    @dog = Dog.find(params[:id])
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(params[:dog])

    respond_to do |format|
      if @dog.save
        # commented out html to test 500 error
        # format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        # format.json { render json: @dog, status: :created, location: @dog }
        format.js { render text: "New dog added"}

      else
        format.html { render action: "new" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /dogs/1
  # PUT /dogs/1.json
  def update
    @dog = Dog.find(params[:id])
    logger.debug
    respond_to do |format|
      if @dog.update_attributes(params[:dog])
        # format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        # format.json { head :no_content }
        format.js { render text: "Dog updated"}
        logger.debug
      else
        format.html { render action: "edit" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
        logger.debug
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
      format.js
    end
  end




end

app/controllers/location_controller.rb
# location_controller.rb
class LocationsController < ApplicationController
  def show
    render params[:location]
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_addDogForm.html.erb
<%= form_for(dog, remote: true) do |f| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain">
    <legend><%= f.label :name %></legend>
    <%= f.text_field :name, { :data => {:theme => :c}}  %>
  </div>


  <div data-role="fieldcontain">

    <fieldset class="priority"  data-role="controlgroup" data-type="horizontal" data-mini="true">
        <legend><%= f.label :priority %></legend><br />
         <label for="radio-choice-d">3</label>
         <%= f.radio_button(:priority, '3', :type => 'radio', :id => "radio-choice-d", :theme => "a")  %>
         <label for="radio-choice-e">2</label>
         <%= f.radio_button(:priority, '2', :type => 'radio', :id => "radio-choice-e", :theme => "a") %>
         <label for="radio-choice-c">1</label>
         <%= f.radio_button(:priority, '1', :type => 'radio', :id => "radio-choice-c", :theme => "a") %>
    </fieldset>


  </div>


  <div data-role="fieldcontain">
    <legend><%= f.label :site %></legend>
    <%= f.select(:site,['TLAC','51st and Mueller','Brodie','SoCo','Lakeline']) %>

    <div id="site-directions">
        <a href="#site-directions" id="site-directions-btn" data-role="button" data-mini="true" data-inline="true" data-icon="info" data-theme="c" data-rel="popup" data-position-to="window" data-transition="pop">Get Directions</a>
    </div>
  </div>


<div data-role="fieldcontain">
  <fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
      <legend><%= f.label :bio %></legend><br />
       <label for="radio-choice-d">Complete</label>
       <%= f.radio_button(:bio, 'Complete', :type => 'radio', :id => "radio-choice-d", :theme => "a")  %>
       <label for="radio-choice-e">Outdated</label>
       <%= f.radio_button(:bio, 'Outdated', :type => 'radio', :id => "radio-choice-e", :theme => "a") %>
       <label for="radio-choice-c">Incomplete</label>
       <%= f.radio_button(:bio, 'Incomplete', :type => 'radio', :id => "radio-choice-c", :theme => "a") %>
  </fieldset>
</div>


<div data-role="fieldcontain">
  <fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
      <legend><%= f.label :photo %></legend><br />
       <label for="radio-choice-d">Complete</label>
       <%= f.radio_button(:photo, 'Complete', :type => 'radio', :id => "radio-choice-d", :class => "photo-complete", :theme => "a")  %>
       <label for="radio-choice-e">Outdated</label>
       <%= f.radio_button(:photo, 'Outdated', :type => 'radio', :id => "radio-choice-e", :class => "photo-outdated", :theme => "a") %>
       <label for="radio-choice-c">Incomplete</label>
       <%= f.radio_button(:photo, 'Incomplete', :type => 'radio', :id => "radio-choice-c", :class => "photo-incomplete", :theme => "a") %>

  </fieldset>

    <div id="upload-photo">
    <a href="#upload-popup" id="upload-photo-btn" data-role="button" data-mini="true" data-inline="true" data-icon="edit" data-theme="c" data-rel="popup" data-position-to="window" data-transition="pop">Upload Photos</a>
    </div>

</div>


<div data-role="fieldcontain">
  <fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
      <legend><%= f.label :video %></legend><br />
       <label for="radio-choice-d">Complete</label>
       <%= f.radio_button(:video, 'Complete', :type => 'radio', :id => "radio-choice-d", :class => "video-complete", :theme => "a")  %>
       <label for="radio-choice-e">Outdated</label>
       <%= f.radio_button(:video, 'Outdated', :type => 'radio', :id => "radio-choice-e", :class => "video-outdated", :theme => "a") %>
       <label for="radio-choice-c">Incomplete</label>
       <%= f.radio_button(:video, 'Incomplete', :type => 'radio', :id => "radio-choice-c", :class => "video-incomplete", :theme => "a") %>  
  </fieldset>

    <div id="upload-video">
    <a href="#upload-popup" id="upload-video-btn" data-role="button" data-mini="true" data-inline="true" data-icon="edit" data-theme="c" data-rel="popup" data-position-to="window" data-transition="pop">Upload Video</a>
    </div>

</div>


  <div data-role="fieldcontain">
    <legend><%= f.label :notes %></legend>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit "value" => "Update", "data-theme" => "g" %>
    <fieldset class="ui-grid-a">
        <div class="ui-block-a"><%= link_to 'Cancel', dogs_path, { "data-role" => "button" } %></div>
        <div class="ui-block-b"><%= link_to 'Delete', dog, method: :delete, data: { confirm: 'Are you sure?', role: "button", theme: "d" }, remote: true %></div>
    </fieldset>
  </div>

<% end %>

app/views/dogs/_mobilefooter.html.erb
    <div id="footer" data-role="navbar" data-position="fixed" data-iconpos="top" data-theme="a">
        <ul>
            <li><a href="#favs-popup" data-rel="popup" data-icon="star" data-theme="a" data-role="button" data-inline="true" data-position-to="window"  data-transition="pop">Favs</a>
            </li>
            <li><a href="#" class="add-dog" data-icon="plus" data-theme="a" data-role="button" data-inline="true" >Add</a></li>
            <!-- <li><%= link_to 'Add', new_dog_path, "data-icon" => "plus", "data-theme" => "a" %></li> -->
            <li><a href="#popupLogin" data-rel="popup" data-position-to="window" data-role="button" data-inline="true" data-icon="check" data-theme="a" data-transition="pop">Sign in</a>
            </li>
        </ul>

        <div data-role="popup" id="popupMenu">
    <div data-role="popup" id="popupLogin" data-theme="c" class="ui-corner-all" data-overlay-theme="a">
        <form>
            <div style="padding:10px 20px;">
              <h3>Please sign in</h3>
              <label for="un" class="ui-hidden-accessible">Username:</label>
              <input type="text" name="user" id="un" value="" placeholder="username" data-theme="c">
              <label for="pw" class="ui-hidden-accessible">Password:</label>
              <input type="password" name="pass" id="pw" value="" placeholder="password" data-theme="c">
              <button type="submit" data-theme="g" data-icon="check">Sign in</button>
            </div>
        </form>
    </div>
</div>
    </div>




<div id="favs-popup" data-role="popup" data-overlay-theme="a" class="ui-content">
   <a href="#" data-rel="back" data-role="button" data-theme="c" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
  <p>Favorites Coming Soon!</p>
</div>

app/views/dogs/_mobileheader.html.erb
<!-- Begin Header -->
<div data-role="header" data-position="fixed">
  <h1><%= @dog.name %>'s Profile</h1>
    <%= link_to 'Back', dogs_path, { "data-icon"  => "back" } %> 
<a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
</div>
<!-- End Header -->

<!-- Begin Panel -->
	<div data-role="panel" data-position-fixed="true" data-theme="a" id="nav-panel">

		<ul data-role="listview" data-theme="a" class="nav-search">
            <li data-icon="delete"><a href="#" data-rel="close">Close menu</a></li>        
            <li><%= link_to 'Home', dogs_path %> </li>
            <li><a href="#panel-fixed-page2">By Location</a></li>
            <li><a href="#panel-fixed-page2">By Need</a></li>
            <li><a href="#panel-fixed-page2">TBD</a></li>
            <li><a href="#panel-fixed-page2">TBD</a></li>
        </ul>
    </div>
<!-- End Panel -->

app/views/dogs/_mobilepanel.html.erb
<!-- Begin Panel -->


	<div data-role="panel" data-position="right" data-iconpos="left" data-position-fixed="true" data-theme="a" id="nav-panel">
		<ul data-role="listview" data-theme="a"  class="nav-search">
            <!-- <li data-icon="false" ><a href="#" data-icon="delete" data-iconpos="notext"data-rel="close">Close menu</a></li> 
            <li data-icon="false" data-iconpos="left"><%= link_to 'Home', dogs_path %>  </li> -->
            <li data-icon="false" data-iconpos="left"><a href="../">Home</a></li>
            <li data-icon="false" ><a href="#" class="panel-by-name">By Name</a></li>
            <li data-icon="false" ><a href="#" class="panel-by-location">By Location</a></li>
            <li data-icon="false" ><a href="#" class="panel-by-priority">By Priority</a></li>
            <li data-icon="false" ><a href="#" class="panel-need-photos">Need Photos</a></li>
            <li data-icon="false" ><a href="#" class="panel-need-videos">Need Videos</a></li>
            <li data-icon="false" ><a href="#" class="panel-need-bios">Need Bios</a></li>
            <li data-icon="false" ><a href="#about-popup" data-rel="popup" data-position-to="window"  data-transition="pop">About</a></li>
        </ul>
    </div>
<!-- End Panel -->



<div id="about-popup" data-role="popup" data-overlay-theme="a" data-theme="c" class="ui-content">
   <a href="#" data-rel="back" data-role="button" data-theme="c" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
  <p>PupPal is still in prototype.<br />Follow developments on <a href="https://github.com/colinmanuel" data-theme="a" >Github</a></p>
</div>

app/views/dogs/destroy.js.erb
$('#<%= dom_id(@dog) %>').fadeOut();

app/views/dogs/index.html.bkp.erb
<h1>Select Dog</h1>



<% @dogs.each do |dog| %>


<table>
  <tr>
    <th>Name</th>
    <th>Site</th>
    <th>Bio</th>
    <th>Photo</th>
    <th>Video</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><%= dog.name %></td>
    <td><%= dog.site %></td>
    <td><%= dog.bio %></td>
    <td><%= dog.photo %></td>
    <td><%= dog.video %></td>
    <td><%= dog.notes %></td>
    <td><%= link_to 'Show', dog %></td>
    <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
    <td><%= link_to 'Delete', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New dog', new_dog_path %>
<%= link_to 'Show', @dog %>



    <%= f.radio_button(:bio, "Complete") %>
    <%= f.label(:bio, "Complete") %>
    <%= f.radio_button(:bio, "Incomplete") %>
    <%= f.label(:bio, "Incomplete") %>
         <%= f.radio_button(:bio, "Update Needed") %>
    <%= f.label(:bio, "Update Needed") %>


     <label for="radio-choice-c">Complete</label>
     <%= f.radio_button(:bio, 'Testing', { :data => {:theme => :a}})  %>

app/views/dogs/indexBKP_072713.html.erb
<!-- Begin Header -->
<div data-role="header" data-position="fixed" >
  <h1>PupPal</h1>
<a data-iconshadow="false" data-shadow="false" data-iconpos="notext" style="display:none" >&nbsp;</a>

<a href="#nav-panel" class="ui-icon-nodisc" data-iconshadow="false" data-role="button" data-icon="bars" data-iconpos="notext" data-shadow="false" >&nbsp;</a>
</div>
<!-- End Header -->

<%= render "mobilepanel" %>

<div id="home-page" data-role="content">



    <h4 class="home-header" data-role="list-divider">Find dogs by:</h4>

<div data-role="collapsible-set" data-inset="false">


<!-- temporary test to see if new dogs populate here -->

<div id="add-dog-form"><%= render "addDogForm" %></div>
<div id="doglist"></div>

<!-- by name -->
    <div id="by-name" data-role="collapsible"  data-content-theme="c" data-inset="false">
        <h3>Name</h3>
            <div class="all-dogs"> 
                <ul data-role="listview" data-filter="true" data-autodividers="true" data-filter-placeholder="Search..." data-inset="false">

                    <% @dogs.each do |dog| %>

                        <li id="<%= dom_id(dog) %>" >
                            <div data-role="collapsible" data-content-theme="c" data-inset="false">
                            <h3><%= dog.name %></h3>
                       


<span>
<!-- begin form -->
<%= render "editDogForm" %>

<!-- /end form -->
</span>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
    </div>



<!-- by priority -->

<div id="by-priority" data-role="collapsible" data-theme="c" data-content-theme="c" data-inset="false">
            <h3>Priority</h3>                    

            <div data-role="collapsible" data-theme="d">
                <h3 class="ui-link-inherit">High <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.high.count %></span></h3>
                <ul data-role="listview" data-count-theme="a">
                    <% Dog.high.each do |dog| %>
                        <li>
                            <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                            <h3><%= dog.name %> <p class="ui-li-aside"><%= dog.site %></p></h3>
                            <% end %>
                        </li>
                    <% end %>
                </ul>  
            </div><!-- /high -->

            <div data-role="collapsible" data-theme="e">
                <h3>Medium <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.med.count%></span></h3>
                <ul data-role="listview" data-count-theme="a">
                    <% Dog.med.each do |dog| %>
                        <li>
                            <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                            <h3><%= dog.name %> <p class="ui-li-aside"><%= dog.site %></p></h3>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </div><!-- /medium -->

            <div data-role="collapsible" data-theme="g">
                <h3>Low <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.low.count%></span></h3>
                    <ul data-role="listview" data-count-theme="a">
                        <% Dog.low.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %> <p class="ui-li-aside"><%= dog.site %></p></h3>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>    
            </div><!-- /low -->

</div>
             
<!-- by location -->
<div id="by-location" data-role="collapsible" data-theme="c" data-content-theme="c" data-inset="false">
            <h3>Location</h3>                    
            <div data-role="collapsible" data-theme="b">
                <h3>TLAC <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.tlac.count%></span></h3>
                <ul data-role="listview" >
                        <% Dog.tlac.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %></h3>
                                <% end %>
                            </li>
                        <% end %>
                </ul>
            </div><!-- /tlac -->

            <div data-role="collapsible" data-theme="d">
                <h3>51st and Mueller <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.mueller.count%></span></h3>
                    <ul data-role="listview" >
                        <% Dog.mueller.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %></h3>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>
            </div><!-- /mueller -->

            <div data-role="collapsible" data-theme="e">
                <h3>Brodie <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.brodie.count%></span></h3>
                    <ul data-role="listview" >
                        <% Dog.brodie.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %></h3>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>    
            </div><!-- /brodie -->


            <div data-role="collapsible" data-theme="f">
                <h3>SoCo <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.soco.count%></span></h3>
                    <ul data-role="listview" >
                        <% Dog.soco.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %></h3>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>
            </div><!-- /soco -->

            <div data-role="collapsible" data-theme="g">
                <h3>Lakeline <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.lakeline.count%></span></h3>
                    <ul data-role="listview" >
                        <% Dog.lakeline.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %></h3>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>
            </div><!-- /lakeline -->

</div>
             
<!-- by need -->

<div id="by-need" data-role="collapsible" data-theme="c" data-content-theme="c" data-inset="false">
            <h3>Need</h3>                    
            <div id="need-photos" data-role="collapsible" data-theme="d">
                <h3>Photos <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.needphotos.count%></span></h3>
                <ul data-role="listview" data-count-theme="a">
                    <% Dog.needphotos.each do |dog| %>
                        <li>
                            <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                            <h3><%= dog.name %> <p class="ui-li-aside"><%= dog.site %></p></h3>
                            <% end %>
                        </li>
                    <% end %>
                </ul>  
            </div><!-- /high -->

            <div id="need-videos" data-role="collapsible" data-theme="f">
                <h3>Videos <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.needvideos.count%></span></h3>
                <ul data-role="listview" data-count-theme="a">
                    <% Dog.needvideos.each do |dog| %>
                        <li>
                            <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                            <h3><%= dog.name %> <p class="ui-li-aside"><%= dog.site %></p></h3>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </div><!-- /medium -->

            <div id="need-bios" data-role="collapsible" data-theme="g">
                <h3>Bios <span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= Dog.needbios.count%></span></h3>
                    <ul data-role="listview" data-count-theme="a">
                        <% Dog.needbios.each do |dog| %>
                            <li>
                                <%= link_to edit_dog_path(dog), {"data-transition" => "slidefade"}  do %>
                                <h3><%= dog.name %> <p class="ui-li-aside"><%= dog.site %></p></h3>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>    
            </div><!-- /low -->
</div> <!-- /collapsible set -->

</div>      







</div>


<%= render "mobilefooter" %>

app/views/dogs/location.html.erb
<!-- Begin Header -->
<div data-role="header" data-position="fixed">
  <h1>Find Dogs By Location</h1>
    <%= link_to 'Back', dogs_path, { "data-icon"  => "back", "data-iconpos" => "notext" } %> 

<a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
</div>
<!-- End Header -->

<%= render "mobilepanel" %>



<div data-role="content">
<h1 style="text-align:center;">Coming Soon</h1>
</div>


<%= render "mobilefooter" %>

app/views/dogs/old/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/old/index.html.erb
<h1>Listing dogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Site</th>
    <th>Bio</th>
    <th>Photo</th>
    <th>Video</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dogs.each do |dog| %>
  <tr>
    <td><%= dog.name %></td>
    <td><%= dog.priority %></td>
    <td><%= dog.site %></td>
    <td><%= dog.bio %></td>
    <td><%= dog.photo %></td>
    <td><%= dog.video %></td>
    <td><%= dog.notes %></td>
    <td><%= link_to 'Show', dog %></td>
    <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
    <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/old/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dog.name %>
</p>

<p>
  <b>Priority:</b>
  <%= @dog.priority %>
</p>

<p>
  <b>Site:</b>
  <%= @dog.site %>
</p>

<p>
  <b>Bio:</b>
  <%= @dog.bio %>
</p>

<p>
  <b>Photo:</b>
  <%= @dog.photo %>
</p>

<p>
  <b>Video:</b>
  <%= @dog.video %>
</p>

<p>
  <b>Notes:</b>
  <%= @dog.notes %>
</p>


<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<!-- Begin Header -->
<div data-role="header" data-position="fixed">
  <h1><%= @dog.name %>'s Profile</h1>
    <%= link_to 'Back', dogs_path, { "data-icon"  => "back", "data-iconpos" => "notext", "data-rel" => "back" } %> 


<a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
</div>
<!-- End Header -->

<%= render "mobilepanel" %>

<div data-role="content">
<p id="notice"><%= notice %></p>

<table data-role="table" id="movie-table" data-mode="reflow" class="ui-responsive table-stroke">
  <thead>
    <tr>
      <th data-priority="1">Name</th>
      <th data-priority="persist">Priority</th>
      <th data-priority="2">Site</th>
      <th data-priority="3">Bio</th>
      <th data-priority="4">Photo</th>
      <th data-priority="5">Video</th>
      <th data-priority="6">Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @dog.name %></td>
      <td><%= @dog.priority %></td>
      <td><%= @dog.site %></td>
      <td><%= @dog.bio %></td>
      <td><%= @dog.photo %></td>
      <td><%= @dog.video %></td>
      <td><%= @dog.notes %></td>
    </tr> 
  </tbody>
</table>


<%= link_to 'Edit Profile', edit_dog_path(@dog), { "data-role" => "button", "data-theme"  => "f" } %>
</div>